### ISSUE TITLE
Support for Dictionary?

### ISSUE THREAD

**Issue by univeous** [HotariTobu/gd-data-binding#22]
It would be easier to integrate this plugin into my existing system if it could be bind to Dictionary like this
```GDscript
var dict := {
	"value" : 0.0
}
var _data = BindingSource.new(dict)

func _ready():
	_data.bind("value").to_slider($Col1/HSlider)
```

**Comment by univeous** [comment]
Another approach:
```GDscript
var dict := {
	"value" : 0.0
}
var _data = BindingSource.new(self)


func _ready():
	_data.bind("dict").using(func(d):return str(d.value)).to_label($Col1/DisplayRow/ValueLabel)
	_data.bind("dict").using(func(d):return d.value).to_slider($Col1/HSlider)
```

There is no problem with the display, but there will be problems when updating the data. 
Perhaps providing a way to customize how the data is updated could be a solution. Providing a convenient using function for the key of the dict would be nice.

**Comment by HotariTobu** [comment]
Please wait for the release of v1.1.0
